modLoader="javafml"
loaderVersion="[46,)"
license="MIT License"
[[mods]]
modId="hardcorecontrol"
version="${file.jarVersion}"
displayName="Hardcore Control"
displayURL="https://www.curseforge.com/minecraft/mc-mods/hardcore-control"
updateJSONURL="https://github.com/mactso/HardcoreControl/raw/main/update.json"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='Hardcore Control.'
[[dependencies.hardcorecontrol]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.hardcorecontrol]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="SERVER"


