# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
loaderVersion="[55,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"
[[mods]]
modId="hardcorecontrol"
version="${file.jarVersion}"
displayName="Hardcore Control"
displayURL="https://www.curseforge.com/minecraft/mc-mods/hardcore-control"
updateJSONURL="https://github.com/mactso/HardcoreControl/raw/main/update.json"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='Hardcore Control.'
[[dependencies.hardcorecontrol]]
    modId="forge"
    mandatory=true
    versionRange="[55,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.hardcorecontrol]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.5,1.22)"
    ordering="NONE"
    side="SERVER"
# side="BOTH", "CLIENT?", "SERVER"

